### ISSUE TITLE
Pokeblocks do not work

### ISSUE THREAD

**Issue by PokeGamerGuy** [BuffelSaft/pokeemerald#340] opened 2022-04-29 12:50 UTC
As soon as you select your berry in the berry mixer the game glitches out and freezes.Sometimes it distorts the image and sometimes it doesn't.

**Comment by BuffelSaft** [comment] 2022-05-07 02:56
Duplicate of #112. Already fixed for the next version fortunately!

**Closed by BuffelSaft** 2022-05-07 02:56 UTC

**Comment by LimeAndry7** [comment] 2025-09-06 10:51
but it isn't fixed! I have the latest 1.13 version and still have this bug. Berry blender just freezes the game after you select the berry
